# Item Tables
The purpose of this notebook is to explore our data tables and produce tables of appearance probabilities and mark ups.

In [37]:
import pandas as pd
from os.path import join
import numpy as np
data_folder="../static/item-data"

In [32]:
general_store_df=pd.read_csv(join(data_folder,"mundane.csv"))
general_store_df=general_store_df[["Type","Subtype"]].drop_duplicates()
general_store_df["probability"]=0.0
general_store_df["mark_up"]=1.2
general_store_df["Level"]=1

In [33]:
general_store_df.loc[general_store_df["Type"]=="Misc","probability"]=0.8

In [34]:
general_store_df.loc[general_store_df["Subtype"]=="Misc","probability"]=0.7
general_store_df.loc[general_store_df["Subtype"]=="Light","probability"]=0.2
general_store_df.loc[general_store_df["Subtype"]=="Simple","probability"]=0.2

In [35]:
general_store_df.to_csv(join(data_folder,"general_store.csv"))

In [36]:
general_store_df

          Type  Subtype  probability  mark_up  Level
0        Armor    Heavy          0.0      1.2      1
4        Armor    Light          0.2      1.2      1
7        Armor   Medium          0.0      1.2      1
12       Armor   Shield          0.0      1.2      1
13        Misc     Ammo          0.8      1.2      1
20        Misc    Focus          0.8      1.2      1
33        Misc     Game          0.8      1.2      1
38        Misc     Gear          0.8      1.2      1
121       Misc     Misc          0.7      1.2      1
124       Misc  Service          0.8      1.2      1
125       Misc    Tools          0.8      1.2      1
160  Transport      Air          0.0      1.2      1
161  Transport   Animal          0.0      1.2      1
169  Transport     Misc          0.7      1.2      1
173  Transport     Ship          0.0      1.2      1
179     Weapon  Martial          0.0      1.2      1
202     Weapon   Simple          0.2      1.2      1

                         Name   Weight       Type Subtype Value Unit  mark_up
14   Alchemist's Fire (flask)    1 lb.       Misc    Ammo    50   gp      1.2
15                Arrows (20)    1 lb.       Misc    Ammo     1   gp      1.2
17        Crossbow Bolts (20)  1.5 lb.       Misc    Ammo     1   gp      1.2
19         Holy water (flask)    1 lb.       Misc    Ammo    25   gp      1.2
18         Sling Bullets (20)  1.5 lb.       Misc    Ammo     4   cp      1.2
..                        ...      ...        ...     ...   ...  ...      ...
171                   Chariot  100 lb.  Transport    Misc   250   gp      1.2
172                     Wagon  400 lb.  Transport    Misc    35   gp      1.2
202                      Club    2 lb.     Weapon  Simple     1   sp      1.2
204                 Greatclub   10 lb.     Weapon  Simple     2   sp      1.2
206                   Javelin    2 lb.     Weapon  Simple     5   sp      1.2

[121 rows x 7 columns]